### ISSUE TITLE
Use keys `no_outgen` and `extra_execution_files` from config

### ISSUE THREAD

**Issue by MasloMaslane** [sio2project/sinol-make#100]
`no_outgen` and `extra_execution_files` were merged into oioioi in https://github.com/sio2project/oioioi/pull/243

**Comment by MasloMaslane** [comment]
@tonowak do we want to support these? `no_outgen` means that output tests aren’t generated and `extra_execution_files` are copied into working directory during running of the solutions

**Comment by tonowak** [comment]
In which situations those are useful?

**Comment by MasloMaslane** [comment]
I have no idea, but I guess it must have been needed at some point, since it was added on sio2.mimuw

**Comment by tonowak** [comment]
I don't know either. We could ask around or ignore it for now.

**Comment by MasloMaslane** [comment]
`no_outgen` was used in "Pisarze" from XXVII OI - the whole config was just `no_outgen: True`.

**Comment by MasloMaslane** [comment]
`extra_execution_files` was used in "Triangles" from CEOI 2018 - it had some java files

**Comment by tonowak** [comment]
OK. Let's ignore those until someone asks for it.

**Comment by tonowak** [comment]
By the way, thanks for checking!

**Comment by MasloMaslane** [comment]
No problem, it was just a search through all configs
