### ISSUE TITLE
TL when output exceeds 65KiB.

### ISSUE THREAD

**Issue by mareksom** [sio2project/sinol-make#146]
**Describe the bug**
If the output of the correct program exceeds 2**16 bytes (65KiB), `sinol-make run` fails the solution with `TL` because the program presumably deadlocks on writing to some pipe buffer.

**To Reproduce**
Create the problem package by running the following command:
```
echo "H4sIAAAAAAAAA+2X24rbMBCGc+2nGHYvuotbnw/gpIW8Q6GXxgdtosayjCWThLLv3nFql3RLGwKxl3bnAyMj2TMyv+aXzA6ZaCpmLybEQeI47Fs3Dp3zdmThBqHrhVHgO+7Ccb3Y9xYQTjmpkU7prAVYiKxlOyXFn567NP6Pwgb9ZacnWwPX6O8GAervh0FE+s/Buf5rx8Lm9jl6gaMo+Iv+/pn+EeofhH39O7efyu+8cf0Dx3jtKRCvyFj/vJ7uCHCF//tRHPf+74cx+f8cnOmP9s/rKXJc4f+D/rgNOOT/c+CT/79pxvpvWrmZage45vwfxF7v/7FL/3+z8Iv+a6tomtvnuOT/vhf81B+v0/kflwv5/wzc87qoupLBKuda2UqXhWla20+GwWsNIuP1wyN8MwAKWSvNDk0L/UB+1EylWqb7lmsGH+HBhdUK3OgRTHCXYNvwRbY7BXuut2A676GUTNXvNOyxe+h1LYz7JFt46ENyjOIssVm9iI59pvljEgA4wSQp8De1T3d3uFti7zNeLdNdW2MA45k2tCsY6x/lfeIb6yiq2+e4VP+B4748/8V+QPU/B/ewripopFI8rxjIRnMsdMCPBSz2CuuflbBlLUtgq3WjEtveYPF2uVVIYSsuPdw5vrJC430tqw8i2zE7r2Ru995hD8tLna0vw9BcVxjvM8OhDN2jyYpdtmHGKUKqM7VLeZnAun9SsLTigusEPFwphmBCtsexC5dM3zm8iCnQNnSqjw1G50VTDANdXcqiEwyHy/QUUktZJdDfklkQBEEQBEEQBEEQBPG/8x2kKN/fACgAAA==" | base64 --decode | tar xzf -
```
The above command should create an `example` directory with the contents of the package.

1. `your_dir$ cd example`
2. `your_dir/example$ sinol-make run`
   ```
   Task: Template package (tag: A)
   Tests that will be run: A0.in
   Running only on example tests.
   Compiling 1 solutions...
   Compilation of file A.cpp was successful.
   
   ---------+------------+
     groups |      A.cpp | 
   -------- | ---------- | 
          0 | TL   0/  1 | 
            |            | 
     points |      0/  1 | 
       time |    ------- | 
     memory |    ------- | 
            |            | 
   -------- | ---------- | 
          0 | TL         | 
            |            | 
   ---------+------------+
   
   Solutions were added: A.cpp
   Use flag --apply-suggestions to apply suggestions.
   ```

**Expected behavior**
The solution `A.cpp` should receive `WA`, because the execution time is extremely low:
```
your_dir/example$ time .cache/executables/A.cpp.e < in/A0.in  > /dev/null

real	0m0,016s
user	0m0,008s
sys	0m0,007s

```

The program `A.cpp` simply writes `2**16+1` bytes to `stdout`:
```
#include <bits/stdc++.h>

int main() {
  constexpr int bytes_to_write = (1 << 16) + 1; // Works with +0, doesn't work with +1.
  for (int i = 0; i < bytes_to_write; i++) {
    std::cout << "x";
  }
  return 0;
}
```

**System (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS
 - Version `sinol-make 1.5.12`

**Additional context**
I suspect that when `subprocess.Popen(stdout=subprocess.PIPE)` is called, the created pipe has a size of `2**16` bytes and unless `sinol-make` reads from the pipe, the solution `A.cpp.e` will not be able to write more. However, `sinol-make` will not start reading unless `A.cpp.e` finishes running. This causes a deadlock which is aborted when the time limit is reached.

Maybe there should be a limit to the size of the output, but it should be much greater than `65KiB` (which is probably platform-dependent anyway). Maybe `1GiB`?

**Comment by tczajka** [comment]
This is a serious bug that is blocking real contest preparation because many problems have outputs longer than that.

**Comment by MasloMaslane** [comment]
I’ll fix it tomorrow
