### ISSUE TITLE
Allow generating only ins/outs instead of both

### ISSUE THREAD

**Issue by A-dead-pixel** [sio2project/sinol-make#154]
**Is your feature request related to a problem? Please describe.**
I can't use this nice tool for generating outs from existing ins in packages without an ingen.

**Describe the solution you'd like**
Additional commands like `ingen` and `outgen` would solve this.

**Describe alternatives you've considered**
New flags for `sinol-make gen`, for example `-o, --outs` and `-i, --ins`.

**Comment by MasloMaslane** [comment]
Thanks for the suggestion, added in `sinol-make v1.5.14`
