### ISSUE TITLE
Check if running on cpu with efficiency cores

### ISSUE THREAD

**Issue by MasloMaslane** [sio2project/sinol-make#158]
Warn user when running on cpu with efficiency cores (sio2jail doesn't work properly on them). Link to a tutorial on how to disable efficiency cores in Linux

**Comment by A-dead-pixel** [comment]
The `perf-stat(1)` [manpage](https://www.man7.org/linux/man-pages/man1/perf-stat.1.html) has some useful info regarding this under "INTEL HYBRID SUPPORT".
It seems that on intel's hybrid cpus one can check the cpu number ranges (?) of the P/E-cores at `/sys/devices/cpu_{core,atom}/cpus` (on my non-alder lake system there is only `/sys/devices/cpu/`).
This functionality was added in linux 5.13, at least according to some [phoronix article](https://www.phoronix.com/news/Linux-5.13-Perf-Tools).

I think that checking whether the `cpu_{core,atom}` folders exist and running sio2jail with `taskset -c $cpu_range` will be a decent workaround to sio2jail not working on the E-cores, which would not require the user to disable E-cores for the whole system.

Alternatively, support for them could be added to sio2jail, which based on the aforementioned manpage seems doable: aside from detecting the cpus' different PMU type ids, we would only need to create additional perf events and aggregate the number of used instructions.

**Comment by MasloMaslane** [comment]
Thanks! We'll probably update sio2jail so that it counts instructions on efficiency cores.
