### ISSUE TITLE
Pascal solutions

### ISSUE THREAD

**Issue by adespawn** [sio2project/sinol-make#183]
Should the script match pascal files when looking for solutions? There is no pascal support in this script...
https://github.com/sio2project/sinol-make/blob/09aaafc9734b8791e2029375ad89ccf77ef19e9d/src/sinol_make/helpers/package_util.py#L57

**Comment by MasloMaslane** [comment]
I think this was copied from the script that the `run` command is based on. I must have forgotten to remove it and I agree that this shouldn't be available. Java compilation is also not implemented.

**Comment by adespawn** [comment]
And it's missing c if i understand this regex correctly.
