### ISSUE TITLE
Add score per test to the detailed `sinol-make run` report.

### ISSUE THREAD

**Issue by Maurycyt** [sio2project/sinol-make#203]
When running solutions on tests in a package with partial points per test (i.e. I can give X% points for a single test), I cannot see how many points a single test received.

There seems to be space for a point total for each test. I marked my proposed place to put the score with a red squiggle:
![image](https://github.com/sio2project/sinol-make/assets/45608748/245712a5-d837-4e10-a502-98b2dcea2101)

I think using a green number would blend too much with the `OK` text, so I suggest using no color for the score.

Of course, I can run a single test and see how many points it receives, but when I want to find tests which receive non-full points, and there's a lot of tests, then I have a lot of work to do.

I see that there's a `--hide-memory` flag, which allows the report to take up half the space. Maybe one could add a `--show-individual-scores` flag?

**Comment by MasloMaslane** [comment]
Added in [sinol-make v1.5.27](https://github.com/sio2project/sinol-make/releases/tag/v1.5.27)
