### ISSUE TITLE
Dangling files in in/ directories

### ISSUE THREAD

**Issue by kezsulap** [sio2project/sinol-make#205]
As far as I can tell: if a newer version of an ingen doesn't create a file with some specific name sinol just assumes it's meant to manually generated test and will still be there, possibly failing newer versions of inwers and causing confusion.

I'm not aware of any solution like specifying in config.yml which tests are manual and which are meant to be generated using ingen. I would expect `sinol-make ingen` could look at the contents of that list and automatically delete dangling files before actually running the generator, keeping only manual ones and generated by up-to-date ingen

(Also there was a command like make clean-gen which was also guessing what to delete based on current version of ingen, maybe sinol-make could have a better version based on the list of manual tests specified in config.yml?) WDYT?

**Comment by MasloMaslane** [comment]
I don't think that keeping a list of manually created tests in config.yml is a good solution. Maybe after running ingen sinol-make could create a list of generated files and after the next run would delete files that were on the list but weren't edited?

**Comment by kezsulap** [comment]
Yeah, I think your solution is better

**Comment by MasloMaslane** [comment]
Fixed in [sinol-make v1.5.27](https://github.com/sio2project/sinol-make/releases/tag/v1.5.27)
