### ISSUE TITLE
sinol-make run continues prior aborted run when it makes no sense

### ISSUE THREAD

**Issue by kezsulap** [sio2project/sinol-make#212]
Example path to reproduce:
Make a package with some tests (correct ins and outs), edit the ingen, run sinol-make ingen, but not outgen, so .out files are outdated, run sinol-make run -s mod.cpp, interrupt with Ctrl+C and only now run sinol-make outgen and try rerunning with sinol-make run -s mod.cpp

Cached execution of the solution is garbage as it was done on mismatched in and out files, even though next run of sinol-make run -s mod.cpp will result in continuing the aborted run and running only uncompleted test cases, rather than running everything from scratch.

I haven't checked what happens if cached run is outdated due to edited modchk.cpp, but I could imagine similar issue could occur

 - OS: Ubuntu
 - Version: 1.5.26

**Comment by MasloMaslane** [comment]
Changing the checker removes all cached test results

**Comment by MasloMaslane** [comment]
Fixed in [sinol-make v1.5.28](https://github.com/sio2project/sinol-make/releases/tag/v1.5.28)
