### ISSUE TITLE
Verifying subtasks with inwer

### ISSUE THREAD

**Issue by kezsulap** [sio2project/sinol-make#218]
AFAIK currently there's no way to verify all tests match the subtasks restrictions they're supposed to other than get inwer to print all subtasks the current test matches and then manually check its output for anything out of line, which obviously is quite error-prone
The easiest solution I'd suggest would be to pass group id to inwer via argv, so when writing inwer we can check for smaller restriction on input size or anything else, but all former packages without using this feature won't break and we're still able to write inwers which ignore that information. 
WDYT?

**Comment by Kostero** [comment]
That's exactly how it was implemented in the original tool. Moreover, you
were able to specify in the config.yml which solutions should pass which
subtasks.

**Comment by MasloMaslane** [comment]
SIO and sinol-make already pass the test name to inwer as first argument.

**Comment by kezsulap** [comment]
OK, that's great, I didn't know that, but since this is something new compared to old version of sinol makefile what do you think about mentioning it in the docs/help of `sinol-make inwer`?
