### ISSUE TITLE
"sinol-make ingen outgen inwer" deletes static tests

### ISSUE THREAD

**Issue by lduraj** [sio2project/sinol-make#235]
**Describe the bug**
Using aggregated command `sinol-make ingen outgen inwer` deletes all tests in the `in/` directory which were static/hand-made. Including the example tests (!). 
Strangely, `sinol-make ingen; sinol-make outgen; sinol-make inwer;` works normally.

**To Reproduce**
1. Run `sinol-make ingen inwer outgen` while having some hand-crafted tests.
2. Not see your tests.
3. Be frustrated.

Here is the example package with generation of `abc0.in` commented out: [abc.zip](https://github.com/sio2project/sinol-make/files/15011360/abc.zip) 

**Expected behavior**
All non-generated tests should stay in place.

**Output**
N/A

**System (please complete the following information):**
 - OS: Ubuntu
 - Version 1.5.29

**Additional context**
Thank you *very much* for deleting my tests ;)

**Comment by MasloMaslane** [comment]
I'm sorry for deleting your tests :( 
[sinol-make v1.5.30](https://github.com/sio2project/sinol-make/releases/tag/v1.5.30) fixes this issue

**Comment by MasloMaslane** [comment]
Also, if you want to run `ingen` and `outgen` you can use the `gen` command.
