### ISSUE TITLE
MacOs tests failing (again)

### ISSUE THREAD

**Issue by adespawn** [sio2project/sinol-make#239]
When running MacOs tests, they are failing at python installation:
https://github.com/Stowarzyszenie-Talent/st-make/actions/runs/8862756736/job/24336065181
(this job is run on a fork of the current sinol-make main branch)

**Comment by MasloMaslane** [comment]
It seems that `macos-latest` now runs with M1 (https://github.com/actions/setup-python/issues/850) and doesn't have Python <=3.9. I think the Python version in tests for MacOS should be bumped to 3.10

**Comment by MasloMaslane** [comment]
And probably all Python versions can be bumped to 3.8, since 3.7 is almost year after end-of-life https://devguide.python.org/versions/
